"""empty message

Revision ID: 192a6f2a542e
Revises: 
Create Date: 2022-05-19 15:27:17.014930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192a6f2a542e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=2000), nullable=True),
    sa.Column('house', sa.String(length=1000), nullable=True),
    sa.Column('time', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_email'), 'houses', ['email'], unique=True)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.String(length=200), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    op.drop_index(op.f('ix_houses_email'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
