"""empty message

Revision ID: 998d27c592b2
Revises: fea11d2c388e
Create Date: 2022-05-17 23:35:23.112233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998d27c592b2'
down_revision = 'fea11d2c388e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_user_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('blogs_user_id_fkey', 'blogs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
