"""add postss

Revision ID: ca75e90b31ff
Revises: b3aa387dffa6
Create Date: 2022-05-19 15:30:27.775665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca75e90b31ff'
down_revision = 'b3aa387dffa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('blogs', sa.String(length=50), nullable=True),
    sa.Column('post', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=False),
    sa.Column('post', sa.String(length=50), nullable=False),
    sa.Column('poster', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poster'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postss')
    op.drop_table('posts')
    # ### end Alembic commands ###
